"""On-screen text overlays + captions (SRT + styled ASS).

Overlays are rendered through libass (a top-positioned ASS style) instead of
FFmpeg drawtext, so long text, Unicode, commas, colons, quotes and
apostrophes can never break a filter graph.
"""
import os
import re

from .ffmpeg_util import sanitize_ass_text


# ---------------------------------------------------------------------------
# Caption templates (CapCut viral/trending styles).
# Each template defines an ASS "Cap" style. Colours are ASS &HAABBGGRR.
# size_scale multiplies the base font size. box=True draws an opaque
# background box behind the text (BorderStyle 3).
# ---------------------------------------------------------------------------
CAPTION_TEMPLATES = {'tiktok_classic': {'label': 'TikTok Classic',
                    'category': 'Trending',
                    'desc': 'White bold caps, black outline, yellow word highlight — the viral '
                            'standard',
                    'font': 'Montserrat',
                    'size_scale': 1.0,
                    'primary': '&H00FFFFFF',
                    'secondary': '&H0000D7FF',
                    'outline_c': '&H90000000',
                    'back_c': '&H90000000',
                    'bold': -1,
                    'italic': 0,
                    'outline': 3,
                    'shadow': 1,
                    'alignment': 2,
                    'box': False,
                    'highlight_mode': 'word',
                    'text_case': 'upper'},
 'hormozi_yellow': {'label': 'Hormozi Yellow',
                    'category': 'Trending',
                    'desc': 'Condensed caps, thick black stroke, yellow spoken word',
                    'font': 'Anton',
                    'size_scale': 1.05,
                    'primary': '&H00FFFFFF',
                    'secondary': '&H0000D7FF',
                    'outline_c': '&H00000000',
                    'back_c': '&H00000000',
                    'bold': 0,
                    'italic': 0,
                    'outline': 4,
                    'shadow': 1,
                    'alignment': 2,
                    'box': False,
                    'highlight_mode': 'word',
                    'text_case': 'upper'},
 'hormozi_cyan': {'label': 'Hormozi Cyan',
                  'category': 'Trending',
                  'desc': 'Condensed caps, thick black stroke, cyan spoken word',
                  'font': 'Anton',
                  'size_scale': 1.05,
                  'primary': '&H00FFFFFF',
                  'secondary': '&H00FFD900',
                  'outline_c': '&H00000000',
                  'back_c': '&H00000000',
                  'bold': 0,
                  'italic': 0,
                  'outline': 4,
                  'shadow': 1,
                  'alignment': 2,
                  'box': False,
                  'highlight_mode': 'word',
                  'text_case': 'upper'},
 'hormozi_green': {'label': 'Hormozi Green',
                   'category': 'Trending',
                   'desc': 'Condensed caps, thick black stroke, green spoken word',
                   'font': 'Anton',
                   'size_scale': 1.05,
                   'primary': '&H00FFFFFF',
                   'secondary': '&H0076E600',
                   'outline_c': '&H00000000',
                   'back_c': '&H00000000',
                   'bold': 0,
                   'italic': 0,
                   'outline': 4,
                   'shadow': 1,
                   'alignment': 2,
                   'box': False,
                   'highlight_mode': 'word',
                   'text_case': 'upper'},
 'hormozi_orange': {'label': 'Hormozi Orange',
                    'category': 'Trending',
                    'desc': 'Condensed caps, thick black stroke, orange spoken word',
                    'font': 'Anton',
                    'size_scale': 1.05,
                    'primary': '&H00FFFFFF',
                    'secondary': '&H000066FF',
                    'outline_c': '&H00000000',
                    'back_c': '&H00000000',
                    'bold': 0,
                    'italic': 0,
                    'outline': 4,
                    'shadow': 1,
                    'alignment': 2,
                    'box': False,
                    'highlight_mode': 'word',
                    'text_case': 'upper'},
 'hormozi_pink': {'label': 'Hormozi Pink',
                  'category': 'Trending',
                  'desc': 'Condensed caps, thick black stroke, hot-pink spoken word',
                  'font': 'Anton',
                  'size_scale': 1.05,
                  'primary': '&H00FFFFFF',
                  'secondary': '&H009948EC',
                  'outline_c': '&H00000000',
                  'back_c': '&H00000000',
                  'bold': 0,
                  'italic': 0,
                  'outline': 4,
                  'shadow': 1,
                  'alignment': 2,
                  'box': False,
                  'highlight_mode': 'word',
                  'text_case': 'upper'},
 'hormozi_red': {'label': 'Hormozi Red',
                 'category': 'Trending',
                 'desc': 'Condensed caps, thick black stroke, red spoken word',
                 'font': 'Anton',
                 'size_scale': 1.05,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H000000FF',
                 'outline_c': '&H00000000',
                 'back_c': '&H00000000',
                 'bold': 0,
                 'italic': 0,
                 'outline': 4,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'upper'},
 'mrbeast': {'label': 'MrBeast',
             'category': 'Trending',
             'desc': 'Huge cartoon caps, yellow text, heavy outline, orange pop word',
             'font': 'Bangers',
             'size_scale': 1.35,
             'primary': '&H0000D7FF',
             'secondary': '&H000066FF',
             'outline_c': '&H00000000',
             'back_c': '&H00000000',
             'bold': 0,
             'italic': 0,
             'outline': 5,
             'shadow': 2,
             'alignment': 2,
             'box': False,
             'highlight_mode': 'wordbig',
             'text_case': 'upper',
             'big_scale': 1.5},
 'podcast_viral': {'label': 'Podcast Viral',
                   'category': 'Trending',
                   'desc': 'Bold caps, white text, electric lime spoken word — interview clips',
                   'font': 'Montserrat',
                   'size_scale': 1.0,
                   'primary': '&H00FFFFFF',
                   'secondary': '&H0035E6A3',
                   'outline_c': '&H90000000',
                   'back_c': '&H90000000',
                   'bold': -1,
                   'italic': 0,
                   'outline': 3,
                   'shadow': 1,
                   'alignment': 2,
                   'box': False,
                   'highlight_mode': 'word',
                   'text_case': 'upper'},
 'kapwing_viral': {'label': 'Kapwing Viral',
                   'category': 'Trending',
                   'desc': 'Bold caps, white text, vibrant blue spoken word',
                   'font': 'Montserrat',
                   'size_scale': 1.0,
                   'primary': '&H00FFFFFF',
                   'secondary': '&H00EB6325',
                   'outline_c': '&H90000000',
                   'back_c': '&H90000000',
                   'bold': -1,
                   'italic': 0,
                   'outline': 3,
                   'shadow': 1,
                   'alignment': 2,
                   'box': False,
                   'highlight_mode': 'word',
                   'text_case': 'upper'},
 'submagic': {'label': 'Submagic',
              'category': 'Trending',
              'desc': 'Cream text, vivid purple spoken word — storytelling reels',
              'font': 'Poppins',
              'size_scale': 1.0,
              'primary': '&H00C3F9FE',
              'secondary': '&H00F755A8',
              'outline_c': '&H90000000',
              'back_c': '&H90000000',
              'bold': -1,
              'italic': 0,
              'outline': 2,
              'shadow': 1,
              'alignment': 2,
              'box': False,
              'highlight_mode': 'word',
              'text_case': 'mixed'},
 'beast_word': {'label': 'Beast Word',
                'category': 'Trending',
                'desc': 'Condensed caps, white text, red giant pop word',
                'font': 'Anton',
                'size_scale': 1.1,
                'primary': '&H00FFFFFF',
                'secondary': '&H000000FF',
                'outline_c': '&H00000000',
                'back_c': '&H00000000',
                'bold': 0,
                'italic': 0,
                'outline': 4,
                'shadow': 1,
                'alignment': 2,
                'box': False,
                'highlight_mode': 'wordbig',
                'text_case': 'upper',
                'big_scale': 1.7},
 'neon_cyan': {'label': 'Neon Cyan',
               'category': 'Glow',
               'desc': 'White text, cyan glowing spoken word — night/gaming vibe',
               'font': 'Montserrat',
               'size_scale': 1.05,
               'primary': '&H00FFFFFF',
               'secondary': '&H00FFFF00',
               'outline_c': '&H90000000',
               'back_c': '&H90000000',
               'bold': -1,
               'italic': 0,
               'outline': 2,
               'shadow': 1,
               'alignment': 2,
               'box': False,
               'highlight_mode': 'wordglow',
               'text_case': 'upper',
               'glow_color': '&H00FFFF00'},
 'neon_pink': {'label': 'Neon Pink',
               'category': 'Glow',
               'desc': 'White text, hot-pink glowing spoken word',
               'font': 'Montserrat',
               'size_scale': 1.05,
               'primary': '&H00FFFFFF',
               'secondary': '&H005500FF',
               'outline_c': '&H90000000',
               'back_c': '&H90000000',
               'bold': -1,
               'italic': 0,
               'outline': 2,
               'shadow': 1,
               'alignment': 2,
               'box': False,
               'highlight_mode': 'wordglow',
               'text_case': 'upper',
               'glow_color': '&H005500FF'},
 'neon_lime': {'label': 'Neon Lime',
               'category': 'Glow',
               'desc': 'White text, lime glowing spoken word',
               'font': 'Montserrat',
               'size_scale': 1.05,
               'primary': '&H00FFFFFF',
               'secondary': '&H0035E6A3',
               'outline_c': '&H90000000',
               'back_c': '&H90000000',
               'bold': -1,
               'italic': 0,
               'outline': 2,
               'shadow': 1,
               'alignment': 2,
               'box': False,
               'highlight_mode': 'wordglow',
               'text_case': 'upper',
               'glow_color': '&H0035E6A3'},
 'neon_gold': {'label': 'Neon Gold',
               'category': 'Glow',
               'desc': 'White text, gold glowing spoken word',
               'font': 'Montserrat',
               'size_scale': 1.05,
               'primary': '&H00FFFFFF',
               'secondary': '&H0000D7FF',
               'outline_c': '&H90000000',
               'back_c': '&H90000000',
               'bold': -1,
               'italic': 0,
               'outline': 2,
               'shadow': 1,
               'alignment': 2,
               'box': False,
               'highlight_mode': 'wordglow',
               'text_case': 'upper',
               'glow_color': '&H0000D7FF'},
 'cyberpunk': {'label': 'Cyberpunk',
               'category': 'Glow',
               'desc': 'Cyan text, neon magenta glowing word — gaming/sci-fi',
               'font': 'Outfit',
               'size_scale': 1.0,
               'primary': '&H00EED322',
               'secondary': '&H005E3FF4',
               'outline_c': '&H90000000',
               'back_c': '&H90000000',
               'bold': -1,
               'italic': 0,
               'outline': 2,
               'shadow': 1,
               'alignment': 2,
               'box': False,
               'highlight_mode': 'wordglow',
               'text_case': 'upper',
               'glow_color': '&H005E3FF4'},
 'dark_psychology': {'label': 'Dark Psychology',
                     'category': 'Glow',
                     'desc': 'White text, blood-red glowing word — thriller/philosophy',
                     'font': 'Outfit',
                     'size_scale': 1.0,
                     'primary': '&H00FFFFFF',
                     'secondary': '&H002626DC',
                     'outline_c': '&H90000000',
                     'back_c': '&H90000000',
                     'bold': -1,
                     'italic': 0,
                     'outline': 2,
                     'shadow': 1,
                     'alignment': 2,
                     'box': False,
                     'highlight_mode': 'wordglow',
                     'text_case': 'upper',
                     'glow_color': '&H002626DC'},
 'fintech': {'label': 'Fintech Wealth',
             'category': 'Glow',
             'desc': 'Fluorescent text, emerald glowing word — finance/crypto',
             'font': 'Outfit',
             'size_scale': 1.0,
             'primary': '&H00FFE7E0',
             'secondary': '&H0081B910',
             'outline_c': '&H90000000',
             'back_c': '&H90000000',
             'bold': -1,
             'italic': 0,
             'outline': 2,
             'shadow': 1,
             'alignment': 2,
             'box': False,
             'highlight_mode': 'wordglow',
             'text_case': 'upper',
             'glow_color': '&H0081B910'},
 'rainbow_glow': {'label': 'Rainbow Glow',
                  'category': 'Glow',
                  'desc': 'White text, magenta-cyan glowing spoken word',
                  'font': 'Poppins',
                  'size_scale': 1.05,
                  'primary': '&H00FFFFFF',
                  'secondary': '&H00FFFFFF',
                  'outline_c': '&H90000000',
                  'back_c': '&H90000000',
                  'bold': -1,
                  'italic': 0,
                  'outline': 2,
                  'shadow': 1,
                  'alignment': 2,
                  'box': False,
                  'highlight_mode': 'wordglow',
                  'text_case': 'upper',
                  'glow_color': '&H00F755A8'},
 'neon_tube': {'label': 'Neon Tube',
               'category': 'Glow',
               'desc': 'Glowing pink neon-tube caps on dark',
               'font': 'Bebas Neue',
               'size_scale': 1.15,
               'primary': '&H005500FF',
               'secondary': '&H00FFFF00',
               'outline_c': '&H005500FF',
               'back_c': '&H90000000',
               'bold': 0,
               'italic': 0,
               'outline': 2,
               'shadow': 3,
               'alignment': 2,
               'box': False,
               'highlight_mode': 'wordglow',
               'text_case': 'upper',
               'glow_color': '&H005500FF'},
 'ali_abdaal': {'label': 'Ali Abdaal',
                'category': 'Aesthetic',
                'desc': 'Soft cream text, pastel blue word — productivity/study',
                'font': 'Poppins',
                'size_scale': 0.9,
                'primary': '&H00EBFBFF',
                'secondary': '&H00F8BD38',
                'outline_c': '&H80000000',
                'back_c': '&H80000000',
                'bold': 0,
                'italic': 0,
                'outline': 1,
                'shadow': 1,
                'alignment': 2,
                'box': False,
                'highlight_mode': 'word',
                'text_case': 'mixed'},
 'iman_luxury': {'label': 'Iman Luxury',
                 'category': 'Aesthetic',
                 'desc': 'Off-white text, champagne gold word — luxury/cinematic',
                 'font': 'Poppins',
                 'size_scale': 0.95,
                 'primary': '&H00FCFAF8',
                 'secondary': '&H000677D9',
                 'outline_c': '&H80000000',
                 'back_c': '&H80000000',
                 'bold': 0,
                 'italic': 0,
                 'outline': 1,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'mixed'},
 'cinema_noir': {'label': 'Cinema Noir',
                 'category': 'Aesthetic',
                 'desc': 'Silver text, white word — dramatic cinematic',
                 'font': 'Montserrat',
                 'size_scale': 0.9,
                 'primary': '&H00F0E8E2',
                 'secondary': '&H00FFFFFF',
                 'outline_c': '&H80000000',
                 'back_c': '&H80000000',
                 'bold': 0,
                 'italic': 0,
                 'outline': 1,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'mixed'},
 'vox_explainer': {'label': 'Vox Explainer',
                   'category': 'Aesthetic',
                   'desc': 'Off-white text, bright yellow word — video essays',
                   'font': 'Poppins',
                   'size_scale': 0.9,
                   'primary': '&H00FCFAF8',
                   'secondary': '&H0024BFFB',
                   'outline_c': '&H80000000',
                   'back_c': '&H80000000',
                   'bold': 0,
                   'italic': 0,
                   'outline': 1,
                   'shadow': 1,
                   'alignment': 2,
                   'box': False,
                   'highlight_mode': 'word',
                   'text_case': 'mixed'},
 'cinema_gold': {'label': 'Cinema Gold',
                 'category': 'Aesthetic',
                 'desc': 'Off-white text, vintage gold word — cinematic shorts',
                 'font': 'Poppins',
                 'size_scale': 0.9,
                 'primary': '&H00FAFAFA',
                 'secondary': '&H00048ACA',
                 'outline_c': '&H80000000',
                 'back_c': '&H80000000',
                 'bold': 0,
                 'italic': 0,
                 'outline': 1,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'mixed'},
 'elegant_serif': {'label': 'Elegant Serif',
                   'category': 'Aesthetic',
                   'desc': 'Refined serif, gold word — elegant minimal',
                   'font': 'Georgia',
                   'size_scale': 0.9,
                   'primary': '&H00FFFFFF',
                   'secondary': '&H0000D7FF',
                   'outline_c': '&H80000000',
                   'back_c': '&H80000000',
                   'bold': 0,
                   'italic': 1,
                   'outline': 1,
                   'shadow': 1,
                   'alignment': 2,
                   'box': False,
                   'highlight_mode': 'word',
                   'text_case': 'mixed'},
 'nordic_clean': {'label': 'Nordic Clean',
                  'category': 'Aesthetic',
                  'desc': 'White text, slate word — calm minimal design',
                  'font': 'Outfit',
                  'size_scale': 0.9,
                  'primary': '&H00FFFFFF',
                  'secondary': '&H00B8A394',
                  'outline_c': '&H80000000',
                  'back_c': '&H80000000',
                  'bold': 0,
                  'italic': 0,
                  'outline': 1,
                  'shadow': 1,
                  'alignment': 2,
                  'box': False,
                  'highlight_mode': 'word',
                  'text_case': 'mixed'},
 'clean_tech': {'label': 'Clean Tech',
                'category': 'Aesthetic',
                'desc': 'White text, electric blue word — SaaS/product',
                'font': 'Outfit',
                'size_scale': 0.9,
                'primary': '&H00FFFFFF',
                'secondary': '&H00F8BD38',
                'outline_c': '&H80000000',
                'back_c': '&H80000000',
                'bold': 0,
                'italic': 0,
                'outline': 1,
                'shadow': 1,
                'alignment': 2,
                'box': False,
                'highlight_mode': 'word',
                'text_case': 'mixed'},
 'script_accent': {'label': 'Script Accent',
                   'category': 'Aesthetic',
                   'desc': 'Clean sans text, gold handwritten accent word',
                   'font': 'Poppins',
                   'size_scale': 0.9,
                   'primary': '&H00FFFFFF',
                   'secondary': '&H0000D7FF',
                   'outline_c': '&H80000000',
                   'back_c': '&H80000000',
                   'bold': 0,
                   'italic': 0,
                   'outline': 1,
                   'shadow': 1,
                   'alignment': 2,
                   'box': False,
                   'highlight_mode': 'word',
                   'text_case': 'mixed'},
 'purple_pill': {'label': 'Purple Pill',
                 'category': 'Highlight',
                 'desc': 'White caps, spoken word on purple pill',
                 'font': 'Montserrat',
                 'size_scale': 1.0,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H00FFFFFF',
                 'outline_c': '&H90000000',
                 'back_c': '&H90000000',
                 'bold': -1,
                 'italic': 0,
                 'outline': 2,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'wordbox',
                 'text_case': 'upper',
                 'box_color': '&H00DC279B'},
 'yellow_pill': {'label': 'Yellow Pill',
                 'category': 'Highlight',
                 'desc': 'White caps, spoken word on yellow pill',
                 'font': 'Montserrat',
                 'size_scale': 1.0,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H00000000',
                 'outline_c': '&H90000000',
                 'back_c': '&H90000000',
                 'bold': -1,
                 'italic': 0,
                 'outline': 2,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'wordbox',
                 'text_case': 'upper',
                 'box_color': '&H0000D7FF'},
 'red_pill': {'label': 'Red Pill',
              'category': 'Highlight',
              'desc': 'White caps, spoken word on red pill',
              'font': 'Montserrat',
              'size_scale': 1.0,
              'primary': '&H00FFFFFF',
              'secondary': '&H00FFFFFF',
              'outline_c': '&H90000000',
              'back_c': '&H90000000',
              'bold': -1,
              'italic': 0,
              'outline': 2,
              'shadow': 1,
              'alignment': 2,
              'box': False,
              'highlight_mode': 'wordbox',
              'text_case': 'upper',
              'box_color': '&H002626DC'},
 'blue_pill': {'label': 'Blue Pill',
               'category': 'Highlight',
               'desc': 'White caps, spoken word on blue pill',
               'font': 'Montserrat',
               'size_scale': 1.0,
               'primary': '&H00FFFFFF',
               'secondary': '&H00FFFFFF',
               'outline_c': '&H90000000',
               'back_c': '&H90000000',
               'bold': -1,
               'italic': 0,
               'outline': 2,
               'shadow': 1,
               'alignment': 2,
               'box': False,
               'highlight_mode': 'wordbox',
               'text_case': 'upper',
               'box_color': '&H00EB6325'},
 'green_pill': {'label': 'Green Pill',
                'category': 'Highlight',
                'desc': 'White caps, spoken word on green pill',
                'font': 'Montserrat',
                'size_scale': 1.0,
                'primary': '&H00FFFFFF',
                'secondary': '&H00000000',
                'outline_c': '&H90000000',
                'back_c': '&H90000000',
                'bold': -1,
                'italic': 0,
                'outline': 2,
                'shadow': 1,
                'alignment': 2,
                'box': False,
                'highlight_mode': 'wordbox',
                'text_case': 'upper',
                'box_color': '&H0035E6A3'},
 'black_pill': {'label': 'Black Pill',
                'category': 'Highlight',
                'desc': 'White caps, spoken word on black pill',
                'font': 'Montserrat',
                'size_scale': 1.0,
                'primary': '&H00FFFFFF',
                'secondary': '&H0000D7FF',
                'outline_c': '&H90000000',
                'back_c': '&H90000000',
                'bold': -1,
                'italic': 0,
                'outline': 2,
                'shadow': 1,
                'alignment': 2,
                'box': False,
                'highlight_mode': 'wordbox',
                'text_case': 'upper',
                'box_color': '&H00000000'},
 'cyan_pill': {'label': 'Cyan Pill',
               'category': 'Highlight',
               'desc': 'White caps, spoken word on cyan pill',
               'font': 'Montserrat',
               'size_scale': 1.0,
               'primary': '&H00FFFFFF',
               'secondary': '&H00000000',
               'outline_c': '&H90000000',
               'back_c': '&H90000000',
               'bold': -1,
               'italic': 0,
               'outline': 2,
               'shadow': 1,
               'alignment': 2,
               'box': False,
               'highlight_mode': 'wordbox',
               'text_case': 'upper',
               'box_color': '&H00FFFF00'},
 'highlighter_yellow': {'label': 'Highlighter Yellow',
                        'category': 'Highlight',
                        'desc': 'Marker swipe behind spoken word — study/notes vibe',
                        'font': 'Poppins',
                        'size_scale': 1.0,
                        'primary': '&H00FFFFFF',
                        'secondary': '&H00000000',
                        'outline_c': '&H90000000',
                        'back_c': '&H90000000',
                        'bold': -1,
                        'italic': 0,
                        'outline': 2,
                        'shadow': 1,
                        'alignment': 2,
                        'box': False,
                        'highlight_mode': 'wordbox',
                        'text_case': 'mixed',
                        'box_color': '&H0000D7FF'},
 'highlighter_pink': {'label': 'Highlighter Pink',
                      'category': 'Highlight',
                      'desc': 'Pink marker swipe behind spoken word',
                      'font': 'Poppins',
                      'size_scale': 1.0,
                      'primary': '&H00FFFFFF',
                      'secondary': '&H00000000',
                      'outline_c': '&H90000000',
                      'back_c': '&H90000000',
                      'bold': -1,
                      'italic': 0,
                      'outline': 2,
                      'shadow': 1,
                      'alignment': 2,
                      'box': False,
                      'highlight_mode': 'wordbox',
                      'text_case': 'mixed',
                      'box_color': '&H009948EC'},
 'red_box_sweep': {'label': 'Red Box Sweep',
                   'category': 'Highlight',
                   'desc': 'Off-white caps, red box sweeps behind spoken word',
                   'font': 'Outfit',
                   'size_scale': 1.0,
                   'primary': '&H00FAF6F4',
                   'secondary': '&H00FFFFFF',
                   'outline_c': '&H90000000',
                   'back_c': '&H90000000',
                   'bold': -1,
                   'italic': 0,
                   'outline': 2,
                   'shadow': 1,
                   'alignment': 2,
                   'box': False,
                   'highlight_mode': 'wordbox',
                   'text_case': 'upper',
                   'box_color': '&H004F38E5'},
 'karaoke_fill': {'label': 'Karaoke Fill',
                  'category': 'Highlight',
                  'desc': 'True sing-along: yellow wipes across each word as spoken',
                  'font': 'Montserrat',
                  'size_scale': 1.0,
                  'primary': '&H00FFFFFF',
                  'secondary': '&H000AD6FF',
                  'outline_c': '&H90000000',
                  'back_c': '&H90000000',
                  'bold': -1,
                  'italic': 0,
                  'outline': 2,
                  'shadow': 1,
                  'alignment': 2,
                  'box': False,
                  'highlight_mode': 'karaoke',
                  'text_case': 'upper'},
 'word_big_pop': {'label': 'Word Big Pop',
                  'category': 'Highlight',
                  'desc': 'Spoken word pops bigger + colored',
                  'font': 'Anton',
                  'size_scale': 1.05,
                  'primary': '&H00FFFFFF',
                  'secondary': '&H0000D7FF',
                  'outline_c': '&H00000000',
                  'back_c': '&H00000000',
                  'bold': 0,
                  'italic': 0,
                  'outline': 4,
                  'shadow': 1,
                  'alignment': 2,
                  'box': False,
                  'highlight_mode': 'wordbig',
                  'text_case': 'upper',
                  'big_scale': 1.8},
 'word_pop': {'label': 'Word Pop',
              'category': 'Word',
              'desc': 'Bold caps karaoke, yellow word — high-energy hooks',
              'font': 'Anton',
              'size_scale': 1.05,
              'primary': '&H00FFFFFF',
              'secondary': '&H0000D7FF',
              'outline_c': '&H00000000',
              'back_c': '&H00000000',
              'bold': 0,
              'italic': 0,
              'outline': 4,
              'shadow': 1,
              'alignment': 2,
              'box': False,
              'highlight_mode': 'word',
              'text_case': 'upper'},
 'single_word_flash': {'label': 'Single Word Flash',
                       'category': 'Word',
                       'desc': 'One giant word at a time — Hormozi/MrBeast style',
                       'font': 'Anton',
                       'size_scale': 1.5,
                       'primary': '&H00FFFFFF',
                       'secondary': '&H0000D7FF',
                       'outline_c': '&H00000000',
                       'back_c': '&H00000000',
                       'bold': 0,
                       'italic': 0,
                       'outline': 5,
                       'shadow': 2,
                       'alignment': 2,
                       'box': False,
                       'highlight_mode': 'wordbig',
                       'text_case': 'upper',
                       'big_scale': 1.3},
 'scale_pop': {'label': 'Scale Pop',
               'category': 'Word',
               'desc': 'Spoken word scales up big + cyan',
               'font': 'Montserrat',
               'size_scale': 1.0,
               'primary': '&H00FFFFFF',
               'secondary': '&H00FFFF00',
               'outline_c': '&H90000000',
               'back_c': '&H90000000',
               'bold': -1,
               'italic': 0,
               'outline': 3,
               'shadow': 1,
               'alignment': 2,
               'box': False,
               'highlight_mode': 'wordbig',
               'text_case': 'upper',
               'big_scale': 1.6},
 'typewriter': {'label': 'Typewriter',
                'category': 'Word',
                'desc': 'Monospace white on black blocks — terminal vibe',
                'font': 'Courier Prime',
                'size_scale': 0.95,
                'primary': '&H00FFFFFF',
                'secondary': '&H0000D7FF',
                'outline_c': '&H00000000',
                'back_c': '&HC8000000',
                'bold': -1,
                'italic': 0,
                'outline': 1,
                'shadow': 0,
                'alignment': 2,
                'box': True,
                'highlight_mode': 'karaoke',
                'text_case': 'mixed'},
 'code_terminal': {'label': 'Code Terminal',
                   'category': 'Word',
                   'desc': 'Terminal white, matrix-green word — dev tutorials',
                   'font': 'Courier Prime',
                   'size_scale': 0.95,
                   'primary': '&H00F9F5F1',
                   'secondary': '&H005EC522',
                   'outline_c': '&H00000000',
                   'back_c': '&HC8000000',
                   'bold': -1,
                   'italic': 0,
                   'outline': 1,
                   'shadow': 0,
                   'alignment': 2,
                   'box': True,
                   'highlight_mode': 'word',
                   'text_case': 'mixed'},
 'hormozi_box': {'label': 'Hormozi Box',
                 'category': 'Frame',
                 'desc': 'White caps on solid black box — Alex Hormozi style',
                 'font': 'Anton',
                 'size_scale': 0.95,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H0000D7FF',
                 'outline_c': '&H00000000',
                 'back_c': '&HC8000000',
                 'bold': 0,
                 'italic': 0,
                 'outline': 1,
                 'shadow': 0,
                 'alignment': 2,
                 'box': True,
                 'highlight_mode': 'word',
                 'text_case': 'upper'},
 'blue_box': {'label': 'Blue Box',
              'category': 'Frame',
              'desc': 'White caps on solid blue box',
              'font': 'Montserrat',
              'size_scale': 0.95,
              'primary': '&H00FFFFFF',
              'secondary': '&H0000D7FF',
              'outline_c': '&H00000000',
              'back_c': '&H00C02800',
              'bold': -1,
              'italic': 0,
              'outline': 1,
              'shadow': 0,
              'alignment': 2,
              'box': True,
              'highlight_mode': 'word',
              'text_case': 'upper'},
 'red_box': {'label': 'Red Box',
             'category': 'Frame',
             'desc': 'White caps on solid red box',
             'font': 'Montserrat',
             'size_scale': 0.95,
             'primary': '&H00FFFFFF',
             'secondary': '&H0000D7FF',
             'outline_c': '&H00000000',
             'back_c': '&H002626DC',
             'bold': -1,
             'italic': 0,
             'outline': 1,
             'shadow': 0,
             'alignment': 2,
             'box': True,
             'highlight_mode': 'word',
             'text_case': 'upper'},
 'caption_bar': {'label': 'Caption Bar',
                 'category': 'Frame',
                 'desc': 'White text on rounded dark bar — podcast style',
                 'font': 'Poppins',
                 'size_scale': 0.9,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H0000D7FF',
                 'outline_c': '&H00000000',
                 'back_c': '&HEB141410',
                 'bold': -1,
                 'italic': 0,
                 'outline': 1,
                 'shadow': 0,
                 'alignment': 2,
                 'box': False,
                 'pill': True,
                 'highlight_mode': 'word',
                 'text_case': 'mixed'},
 'news_bar': {'label': 'News Bar',
              'category': 'Frame',
              'desc': 'Broadcast lower-third bar with headline',
              'font': 'Poppins',
              'size_scale': 0.9,
              'primary': '&H00FFFFFF',
              'secondary': '&H0000D7FF',
              'outline_c': '&H00000000',
              'back_c': '&HF0141414',
              'bold': -1,
              'italic': 0,
              'outline': 1,
              'shadow': 0,
              'alignment': 2,
              'box': True,
              'highlight_mode': 'word',
              'text_case': 'upper'},
 'tiktok_bar': {'label': 'TikTok Bar',
                'category': 'Frame',
                'desc': 'White text on translucent black bar — classic TikTok',
                'font': 'Poppins',
                'size_scale': 0.9,
                'primary': '&H00FFFFFF',
                'secondary': '&H0000D7FF',
                'outline_c': '&H00000000',
                'back_c': '&H99000000',
                'bold': 0,
                'italic': 0,
                'outline': 1,
                'shadow': 0,
                'alignment': 2,
                'box': False,
                'pill': True,
                'highlight_mode': 'word',
                'text_case': 'mixed'},
 'white_card': {'label': 'White Card',
                'category': 'Frame',
                'desc': 'Black bold text on white rounded pill',
                'font': 'Poppins',
                'size_scale': 0.9,
                'primary': '&H00000000',
                'secondary': '&H00DC279B',
                'outline_c': '&H00000000',
                'back_c': '&H00FFFFFF',
                'bold': -1,
                'italic': 0,
                'outline': 1,
                'shadow': 0,
                'alignment': 2,
                'box': False,
                'pill': True,
                'highlight_mode': 'word',
                'text_case': 'mixed'},
 'black_contour': {'label': 'Black Contour',
                   'category': 'Frame',
                   'desc': 'White bold text on solid black pills',
                   'font': 'Poppins',
                   'size_scale': 0.9,
                   'primary': '&H00FFFFFF',
                   'secondary': '&H0000D7FF',
                   'outline_c': '&H00000000',
                   'back_c': '&H00000000',
                   'bold': -1,
                   'italic': 0,
                   'outline': 1,
                   'shadow': 0,
                   'alignment': 2,
                   'box': False,
                   'pill': True,
                   'highlight_mode': 'word',
                   'text_case': 'upper'},
 'minimal_vlog_capsule': {'label': 'Vlog Capsule',
                          'category': 'Frame',
                          'desc': 'Frosted black capsule, tracked uppercase',
                          'font': 'Outfit',
                          'size_scale': 0.85,
                          'primary': '&H00FFFFFF',
                          'secondary': '&H00F8BD38',
                          'outline_c': '&H00000000',
                          'back_c': '&HEB141410',
                          'bold': 0,
                          'italic': 0,
                          'outline': 1,
                          'shadow': 0,
                          'alignment': 2,
                          'box': False,
                          'pill': True,
                          'highlight_mode': 'word',
                          'text_case': 'upper'},
 'minimal_clean': {'label': 'Minimal Clean',
                   'category': 'Monoline',
                   'desc': 'Small clean text, no stroke — cinematic feel',
                   'font': 'Poppins',
                   'size_scale': 0.7,
                   'primary': '&H00FFFFFF',
                   'secondary': '&H0000D7FF',
                   'outline_c': '&H80000000',
                   'back_c': '&H80000000',
                   'bold': 0,
                   'italic': 0,
                   'outline': 0,
                   'shadow': 1,
                   'alignment': 2,
                   'box': False,
                   'highlight_mode': 'word',
                   'text_case': 'mixed'},
 'youtube_style': {'label': 'YouTube Style',
                   'category': 'Monoline',
                   'desc': 'Standard YouTube captions — white on translucent black',
                   'font': 'Arial',
                   'size_scale': 0.85,
                   'primary': '&H00FFFFFF',
                   'secondary': '&H00FFFFFF',
                   'outline_c': '&H00000000',
                   'back_c': '&H99000000',
                   'bold': 0,
                   'italic': 0,
                   'outline': 1,
                   'shadow': 0,
                   'alignment': 2,
                   'box': True,
                   'highlight_mode': 'karaoke',
                   'text_case': 'mixed'},
 'outline_only': {'label': 'Outline Only',
                  'category': 'Monoline',
                  'desc': 'Hollow outlined caps, no fill',
                  'font': 'Outfit',
                  'size_scale': 1.0,
                  'primary': '&HFFFFFFFF',
                  'secondary': '&H0000D7FF',
                  'outline_c': '&H00FFFFFF',
                  'back_c': '&H80000000',
                  'bold': -1,
                  'italic': 0,
                  'outline': 3,
                  'shadow': 0,
                  'alignment': 2,
                  'box': False,
                  'highlight_mode': 'word',
                  'text_case': 'upper'},
 'thin_clean': {'label': 'Thin Clean',
                'category': 'Monoline',
                'desc': 'Thin white text, subtle — documentary lower third',
                'font': 'Outfit',
                'size_scale': 0.8,
                'primary': '&H00FFFFFF',
                'secondary': '&H0035E6A3',
                'outline_c': '&H80000000',
                'back_c': '&H80000000',
                'bold': 0,
                'italic': 0,
                'outline': 1,
                'shadow': 1,
                'alignment': 2,
                'box': False,
                'highlight_mode': 'word',
                'text_case': 'mixed'},
 'meme_top': {'label': 'Meme Top',
              'category': 'Basic',
              'desc': 'Classic Impact meme caps at top of frame',
              'font': 'Impact',
              'size_scale': 1.1,
              'primary': '&H00FFFFFF',
              'secondary': '&H0000D7FF',
              'outline_c': '&H90000000',
              'back_c': '&H90000000',
              'bold': 0,
              'italic': 0,
              'outline': 4,
              'shadow': 0,
              'alignment': 8,
              'box': False,
              'highlight_mode': 'word',
              'text_case': 'upper'},
 'meme_bottom': {'label': 'Meme Bottom',
                 'category': 'Basic',
                 'desc': 'Classic Impact meme caps at bottom',
                 'font': 'Impact',
                 'size_scale': 1.1,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H0000D7FF',
                 'outline_c': '&H90000000',
                 'back_c': '&H90000000',
                 'bold': 0,
                 'italic': 0,
                 'outline': 4,
                 'shadow': 0,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'upper'},
 'comic': {'label': 'Comic',
           'category': 'Basic',
           'desc': 'Cartoon font, yellow word pop',
           'font': 'Fredoka',
           'size_scale': 1.05,
           'primary': '&H00FFFFFF',
           'secondary': '&H0000D7FF',
           'outline_c': '&H90000000',
           'back_c': '&H90000000',
           'bold': -1,
           'italic': 0,
           'outline': 3,
           'shadow': 1,
           'alignment': 2,
           'box': False,
           'highlight_mode': 'word',
           'text_case': 'mixed'},
 'comic_pink': {'label': 'Comic Pink',
                'category': 'Basic',
                'desc': 'Cartoon font, pink word pop',
                'font': 'Fredoka',
                'size_scale': 1.05,
                'primary': '&H00FFFFFF',
                'secondary': '&H009948EC',
                'outline_c': '&H90000000',
                'back_c': '&H90000000',
                'bold': -1,
                'italic': 0,
                'outline': 3,
                'shadow': 1,
                'alignment': 2,
                'box': False,
                'highlight_mode': 'word',
                'text_case': 'mixed'},
 'retro': {'label': 'Retro',
           'category': 'Basic',
           'desc': 'Vintage warm tones, bold caps',
           'font': 'Poppins',
           'size_scale': 1.0,
           'primary': '&H008AF0FE',
           'secondary': '&H00048ACA',
           'outline_c': '&H90441A00',
           'back_c': '&H90441A00',
           'bold': -1,
           'italic': 0,
           'outline': 2,
           'shadow': 1,
           'alignment': 2,
           'box': False,
           'highlight_mode': 'word',
           'text_case': 'upper'},
 'urban_rebel': {'label': 'Urban Rebel',
                 'category': 'Basic',
                 'desc': 'Pale yellow caps, red word — streetwear/hip-hop',
                 'font': 'Anton',
                 'size_scale': 1.05,
                 'primary': '&H008AF0FE',
                 'secondary': '&H004444EF',
                 'outline_c': '&H00000000',
                 'back_c': '&H00000000',
                 'bold': 0,
                 'italic': 0,
                 'outline': 3,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'upper'},
 'warm_pastel': {'label': 'Warm Pastel',
                 'category': 'Basic',
                 'desc': 'Lavender text, coral word — wellness/beauty',
                 'font': 'Poppins',
                 'size_scale': 1.0,
                 'primary': '&H00FFE8F3',
                 'secondary': '&H008571FB',
                 'outline_c': '&H80000000',
                 'back_c': '&H80000000',
                 'bold': 0,
                 'italic': 0,
                 'outline': 1,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'mixed'},
 'creator_pop': {'label': 'Creator Pop',
                 'category': 'Basic',
                 'desc': 'White text, hot-pink word — vlogs/lifestyle',
                 'font': 'Poppins',
                 'size_scale': 1.0,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H009948EC',
                 'outline_c': '&H90000000',
                 'back_c': '&H90000000',
                 'bold': -1,
                 'italic': 0,
                 'outline': 2,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'mixed'},
 'tiktok_hype': {'label': 'TikTok Hype',
                 'category': 'Basic',
                 'desc': 'White text, bright orange word — viral reactions',
                 'font': 'Montserrat',
                 'size_scale': 1.05,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H001673F9',
                 'outline_c': '&H90000000',
                 'back_c': '&H90000000',
                 'bold': -1,
                 'italic': 0,
                 'outline': 3,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'upper'},
 'sports_hype': {'label': 'Sports Hype',
                 'category': 'Basic',
                 'desc': 'Condensed caps, yellow word — sports energy',
                 'font': 'Anton',
                 'size_scale': 1.1,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H0000D7FF',
                 'outline_c': '&H00000000',
                 'back_c': '&H00000000',
                 'bold': 0,
                 'italic': 0,
                 'outline': 4,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'upper'},
 'dark_documentary': {'label': 'Dark Documentary',
                      'category': 'Basic',
                      'desc': 'Pale gray text, crimson word — crime/mystery',
                      'font': 'Poppins',
                      'size_scale': 0.95,
                      'primary': '&H00F9F5F1',
                      'secondary': '&H00481DE1',
                      'outline_c': '&H80000000',
                      'back_c': '&H80000000',
                      'bold': 0,
                      'italic': 0,
                      'outline': 1,
                      'shadow': 1,
                      'alignment': 2,
                      'box': False,
                      'highlight_mode': 'word',
                      'text_case': 'mixed'},
 'desi_dhamaka': {'label': 'Desi Dhamaka',
                  'category': 'Basic',
                  'desc': 'Bold condensed caps, yellow word — South Asian creator style',
                  'font': 'Anton',
                  'size_scale': 1.05,
                  'primary': '&H00FFFFFF',
                  'secondary': '&H0000D7FF',
                  'outline_c': '&H00000000',
                  'back_c': '&H00000000',
                  'bold': 0,
                  'italic': 0,
                  'outline': 4,
                  'shadow': 1,
                  'alignment': 2,
                  'box': False,
                  'highlight_mode': 'word',
                  'text_case': 'upper'},
 'red_text': {'label': 'Red Text',
              'category': 'Basic',
              'desc': 'Bold red caps, dark outline — high alert',
              'font': 'Anton',
              'size_scale': 1.05,
              'primary': '&H000000FF',
              'secondary': '&H0000D7FF',
              'outline_c': '&H00000000',
              'back_c': '&H00000000',
              'bold': 0,
              'italic': 0,
              'outline': 3,
              'shadow': 1,
              'alignment': 2,
              'box': False,
              'highlight_mode': 'word',
              'text_case': 'upper'},
 'green_highlight': {'label': 'Green Highlight',
                     'category': 'Basic',
                     'desc': 'White caps, thin outline, green spoken word',
                     'font': 'Montserrat',
                     'size_scale': 0.9,
                     'primary': '&H00FFFFFF',
                     'secondary': '&H0076E600',
                     'outline_c': '&H90000000',
                     'back_c': '&H90000000',
                     'bold': -1,
                     'italic': 0,
                     'outline': 2,
                     'shadow': 1,
                     'alignment': 2,
                     'box': False,
                     'highlight_mode': 'word',
                     'text_case': 'upper'},
 'lime_highlight': {'label': 'Lime Highlight',
                    'category': 'Basic',
                    'desc': 'White caps, black outline, lime spoken word',
                    'font': 'Montserrat',
                    'size_scale': 1.0,
                    'primary': '&H00FFFFFF',
                    'secondary': '&H0035E6A3',
                    'outline_c': '&H90000000',
                    'back_c': '&H90000000',
                    'bold': -1,
                    'italic': 0,
                    'outline': 3,
                    'shadow': 1,
                    'alignment': 2,
                    'box': False,
                    'highlight_mode': 'word',
                    'text_case': 'upper'},
 'yellow_highlight': {'label': 'Yellow Highlight',
                      'category': 'Basic',
                      'desc': 'White caps, black outline, yellow spoken word',
                      'font': 'Montserrat',
                      'size_scale': 1.0,
                      'primary': '&H00FFFFFF',
                      'secondary': '&H0000D7FF',
                      'outline_c': '&H90000000',
                      'back_c': '&H90000000',
                      'bold': -1,
                      'italic': 0,
                      'outline': 3,
                      'shadow': 1,
                      'alignment': 2,
                      'box': False,
                      'highlight_mode': 'word',
                      'text_case': 'upper'},
 'plain_bold': {'label': 'Plain Bold',
                'category': 'Basic',
                'desc': 'Simple bold white caps, black outline',
                'font': 'Montserrat',
                'size_scale': 1.0,
                'primary': '&H00FFFFFF',
                'secondary': '&H00FFFFFF',
                'outline_c': '&H90000000',
                'back_c': '&H90000000',
                'bold': -1,
                'italic': 0,
                'outline': 3,
                'shadow': 1,
                'alignment': 2,
                'box': False,
                'highlight_mode': 'karaoke',
                'text_case': 'upper'},
 'handwritten': {'label': 'Handwritten',
                 'category': 'Basic',
                 'desc': 'Marker handwriting, gold accent — personal vlogs',
                 'font': 'Caveat',
                 'size_scale': 1.25,
                 'primary': '&H00FFFFFF',
                 'secondary': '&H0000D7FF',
                 'outline_c': '&H90000000',
                 'back_c': '&H90000000',
                 'bold': -1,
                 'italic': 0,
                 'outline': 2,
                 'shadow': 1,
                 'alignment': 2,
                 'box': False,
                 'highlight_mode': 'word',
                 'text_case': 'mixed'}}

CAPTION_TEMPLATE_CATEGORIES = ['Trending', 'Glow', 'Aesthetic', 'Highlight', 'Word', 'Frame', 'Monoline', 'Basic']

DEFAULT_CAPTION_TEMPLATE = "tiktok_classic"


def caption_template_labels():
    """Ordered (key, label) pairs for UI dropdowns."""
    return [(k, v["label"]) for k, v in CAPTION_TEMPLATES.items()]


def make_overlay_text(analysis, max_words=5):
    """Short punchy overlay, never the whole sentence."""
    parts = []
    for p in analysis.phrases or []:
        for w in p.split():
            if w.lower() not in [x.lower() for x in parts]:
                parts.append(w)
    for k in analysis.keywords or []:
        if k.lower() not in [x.lower() for x in parts]:
            parts.append(k)
    return " ".join(parts[:max_words]).upper()


def _ts_srt(sec):
    sec = max(0.0, sec)
    h, rem = int(sec // 3600), sec % 3600
    m, rem = int(rem // 60), rem % 60
    return f"{h:02d}:{m:02d}:{int(rem):02d},{int(rem % 1 * 1000):03d}"


def _ts_ass(sec):
    sec = max(0.0, sec)
    h, rem = int(sec // 3600), sec % 3600
    m, rem = int(rem // 60), rem % 60
    return f"{h}:{m:02d}:{int(rem):02d}.{int(rem % 1 * 100):02d}"


def build_srt(sentence_timings, path):
    with open(path, "w", encoding="utf-8") as f:
        for i, s in enumerate(sentence_timings, 1):
            f.write(f"{i}\n{_ts_srt(s['start'])} --> {_ts_srt(s['end'])}\n{s['text']}\n\n")
    return path


def build_ass(sentence_timings, word_timings, path, font_size=48, highlight=True,
              overlays=None, play_res=(1920, 1080), template=None):
    """Build the ASS file: bottom captions + optional top overlays.

    overlays: list of dicts {text, start, end}. They use the "Top" style
    (alignment 8 = top-center) so no drawtext filter is ever needed.
    template: key from CAPTION_TEMPLATES (CapCut-style caption look).
    """
    tmpl = CAPTION_TEMPLATES.get(template or DEFAULT_CAPTION_TEMPLATE,
                                 CAPTION_TEMPLATES[DEFAULT_CAPTION_TEMPLATE])
    pw, ph = play_res
    cap_size = max(24, int(ph * font_size / 1080 * tmpl["size_scale"]))
    top_size = max(30, int(ph / 20))
    # BorderStyle: 3 = opaque box (Hormozi), 4 = rounded box (pill),
    # else 1 = outline.
    if tmpl.get("pill"):
        border_style = 4
    elif tmpl["box"]:
        border_style = 3
    else:
        border_style = 1
    header = """[Script Info]
ScriptType: v4.00+
PlayResX: %d
PlayResY: %d
WrapStyle: 0
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Cap,%s,%d,%s,%s,%s,%s,%d,%d,0,0,100,100,0,0,%d,%d,%d,%d,40,40,60,1
Style: Top,Arial,%d,&H00FFFFFF,&H000019FF,&H90000000,&H90000000,-1,0,0,0,100,100,0,0,1,3,1,8,60,60,60,1
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
""" % (pw, ph, tmpl["font"], cap_size, tmpl["primary"], tmpl["secondary"],
       tmpl["outline_c"], tmpl["back_c"], tmpl["bold"], tmpl["italic"],
       border_style, tmpl["outline"], tmpl["shadow"], tmpl["alignment"],
       top_size)
    lines = []
    hmode = tmpl.get("highlight_mode", "karaoke")
    tcase = tmpl.get("text_case")

    def _case(w: str) -> str:
        if tcase == "upper":
            return w.upper()
        if tcase == "lower":
            return w.lower()
        return w

    if highlight and word_timings and hmode in ("word", "wordbox", "wordbig", "wordglow"):
        # CapCut "Word Highlight": the FULL sentence stays on screen, but
        # only the CURRENT word is emphasized (non-cumulative). One event per
        # word, each spanning until the next word starts.
        #   word:    current word colored
        #   wordbox: current word on a colored box
        #   wordbig: current word bigger + colored (size emphasis)
        #   wordglow: current word with colored glow outline
        sec = tmpl["secondary"]
        pri = tmpl["primary"]
        box_c = tmpl.get("box_color", "&H00FF0000")
        glow_c = tmpl.get("glow_color", sec)
        big_scale = tmpl.get("big_scale", 1.8)
        big_size = int(cap_size * big_scale)
        words = list(word_timings)
        wi = 0
        for s in sentence_timings:
            seg = []
            while wi < len(words) and words[wi]["end"] <= s["end"] + 0.05:
                seg.append(words[wi])
                wi += 1
            if not seg:
                w0 = _case(s["text"])
                safe = sanitize_ass_text(w0)
                lines.append(
                    f"Dialogue: 0,{_ts_ass(s['start'])},{_ts_ass(s['end'])},"
                    f"Cap,,0,0,0,,{safe}")
                continue
            sent_words = [_case(w["word"]) for w in seg]
            for i, w in enumerate(seg):
                ws, we = w["start"], w["end"]
                if i + 1 < len(seg):
                    we = seg[i + 1]["start"]
                else:
                    we = max(we, s["end"])
                if we <= ws:
                    we = ws + 0.01
                parts = []
                for j, sw_ in enumerate(sent_words):
                    safe = sanitize_ass_text(sw_)
                    if j == i:
                        if hmode == "wordbox":
                            parts.append(
                                "{\\bord6\\3c%s}%s{\\bord%d\\3c%s}" %
                                (box_c, safe, tmpl["outline"],
                                 tmpl["outline_c"]))
                        elif hmode == "wordbig":
                            parts.append(
                                "{\\fs%d\\c%s}%s{\\fs%d\\c%s}" %
                                (big_size, sec, safe, cap_size, pri))
                        elif hmode == "wordglow":
                            parts.append(
                                "{\\c%s\\bord4\\3c%s}%s{\\c%s\\bord%d\\3c%s}" %
                                (sec, glow_c, safe, pri,
                                 tmpl["outline"], tmpl["outline_c"]))
                        else:
                            parts.append("{\\c%s}%s{\\c%s}" % (sec, safe, pri))
                    else:
                        parts.append(safe)
                txt = " ".join(parts)
                lines.append(
                    f"Dialogue: 0,{_ts_ass(ws)},{_ts_ass(we)},"
                    f"Cap,,0,0,0,,{txt}")
    elif highlight and word_timings:
        # karaoke-style per-word highlight
        words = list(word_timings)
        wi = 0
        for s in sentence_timings:
            seg = []
            while wi < len(words) and words[wi]["end"] <= s["end"] + 0.05:
                seg.append(words[wi])
                wi += 1
            if not seg:
                seg = [{"word": s["text"], "start": s["start"], "end": s["end"]}]
            txt = "".join("{\\k%d}%s " % (max(1, int((w["end"] - w["start"]) * 100)),
                                          sanitize_ass_text(w["word"]))
                          for w in seg)
            lines.append(f"Dialogue: 0,{_ts_ass(s['start'])},{_ts_ass(s['end'])},Cap,,0,0,0,,{txt.strip()}")
    else:
        for s in sentence_timings:
            safe = sanitize_ass_text(s["text"])
            lines.append(f"Dialogue: 0,{_ts_ass(s['start'])},{_ts_ass(s['end'])},Cap,,0,0,0,,{safe}")
    for ov in overlays or []:
        txt = sanitize_ass_text(ov["text"])
        if not txt.strip():
            continue
        lines.append(f"Dialogue: 1,{_ts_ass(ov['start'])},{_ts_ass(ov['end'])},Top,,0,0,0,,{txt}")
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + "\n".join(lines) + "\n")
    return path


def youtube_suggest(analysis, scenes, timings):
    """Titles, description, chapters, tags, thumbnail text from the real script data."""
    kws = []
    for s in analysis.sentences:
        kws += s.keywords
    from collections import Counter
    top = [w for w, _ in Counter(kws).most_common(6)]
    topic = analysis.topic.replace("_", " ").title()
    base = " ".join(w.capitalize() for w in top[:4])
    titles = [
        f"{base} Explained: What You Need to Know",
        f"The Truth About {topic} ({base})",
        f"{base} | {topic} Documentary",
    ]
    desc = (f"{base}.\n\nIn this video we break down {topic.lower()} step by step.\n\n"
            f"Topics covered: {', '.join(top)}.\n")
    chapters = []
    for sc, t in zip(scenes, timings):
        m, sec = int(t["start"] // 60), int(t["start"] % 60)
        chapters.append(f"{m:02d}:{sec:02d} - {sc.text[:60]}")
    tags = list(dict.fromkeys(top + [analysis.topic, "documentary", "explainer"]))
    thumb = make_overlay_text(analysis.sentences[0], max_words=4) if analysis.sentences else topic.upper()
    return {"titles": titles, "description": desc, "chapters": chapters,
            "tags": tags, "thumbnail_text": thumb}
